server:
  port: 8040

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  config-location: classpath:mybatis/mybatis-config.xml # mybatis的config文件位置配置
  mapper-locations: classpath:mybatis/mapping/**/*.xml     # 表的xml文件位置配置
  type-aliases-package: com.nz.test.entity.**

logging:
  level:
    com.nz.test.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5050/eureka/,http://127.0.0.1:5051/eureka/