eureka:
  server:
    enable-self-preservation: true # 关闭自我保护模式（缺省为打开）
    peer-eureka-nodes-update-interval-ms: 1000 # 集群节点更新频率,单位:毫秒
    eviction-interval-timer-in-ms: 1000 # 设置清理间隔,单位为毫秒,缺省为60*1000ms
    delta-retention-timer-interval-in-ms: 1000 # 移除队列里过期的租约变更记录的定时任务执行频率,30*1000
    retention-time-in-m-s-in-delta-queue: 1000 # 租约变更记录过期时长,3*60*1000
  instance:
    hostname: master # 主机名: windows - C:\Windows\System32\drivers\etc; linux - /etc/hosts
    lease-renewal-interval-in-seconds: 3 # 心跳时间，即服务续约间隔时间(缺省为30s)
    lease-expiration-duration-in-seconds: 3 # 发呆时间 or 服务失效时间,等待下一次心跳的超时时间,若没收到心跳,则移除instance(缺省为90s)
  client:
    register-with-eureka: false #是否向注册中心注册自己,默认true
    fetch-registry: false # 是否从Eureka注册中心获取注册信息,默认:true
    registry-fetch-interval-seconds: 3 # 客户端拉取服务注册信息间隔,默认为30秒
    health-check:
      enabled: true # 是否启用客户端健康检查,启健康检查依赖spring-boot-starter-actuator
    service-url:
      defaultZone: http://slave1:5051/eureka/ # Eureka服务器的地址;类型为HashMap;缺省的Key为 defaultZone,缺省的Value为 http://localhost:8761/eureka 或 http://${eureka.instance.hostname}:${server.port}/eureka/;如果服务注册中心为高可用集群时,多个注册中心地址以逗号分隔;